name: Base Image CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/docker-publish.yml'
      - 'Dockerfile.base'
      - '.dockerignore.base'
  workflow_dispatch:  # 允许手动触发

jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史以支持版本计算

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: chiupam/workclock:base 